import { Barber, ServiceItem, Appointment, ClientProfile, InventoryProduct, FinancialTransaction, ShopConfig, ShopUnit } from './types';

export const initialUnits: ShopUnit[] = [
  {
    id: 'unit-1',
    name: 'Barbearia Barbershop - Matriz',
    city: 'Goiânia',
    address: 'Av. T-63, 1200 - Bueno',
    phone: '(62) 99999-0001',
    active: true,
  },
  {
    id: 'unit-2',
    name: 'Barbearia Barbershop - Unidade Jardins',
    city: 'Goiânia',
    address: 'Alameda Dom Emanuel, 450 - Alphaville',
    phone: '(62) 99999-0002',
    active: true,
  },
];

export const initialBarbers: Barber[] = [
  {
    id: 'barber-1',
    name: 'João da Silva',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    role: 'Barbeiro Master',
    phone: '(62) 99999-1111',
    commissionRate: 0.50,
    active: true,
    rating: 4.9,
    totalCutsMonth: 124,
    unitId: 'unit-1',
  },
  {
    id: 'barber-2',
    name: 'Carlos Eduardo',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    role: 'Especialista em Barba',
    phone: '(62) 99999-2222',
    commissionRate: 0.50,
    active: true,
    rating: 4.8,
    totalCutsMonth: 98,
    unitId: 'unit-1',
  },
  {
    id: 'barber-3',
    name: 'Mateus Santos',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    role: 'Visagista / Fade',
    phone: '(62) 99999-3333',
    commissionRate: 0.55,
    active: true,
    rating: 4.9,
    totalCutsMonth: 110,
    unitId: 'unit-1',
  },
  {
    id: 'barber-4',
    name: 'Ana Paula',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    role: 'Estética & Pigmentação',
    phone: '(62) 99999-4444',
    commissionRate: 0.50,
    active: true,
    rating: 5.0,
    totalCutsMonth: 85,
    unitId: 'unit-1',
  },
];

export const initialServices: ServiceItem[] = [
  {
    id: 'srv-1',
    name: 'Corte',
    durationMin: 40,
    price: 45.00,
    category: 'cabelo',
    active: true,
    description: 'Corte tesoura ou máquina com lavagem e finalização premium',
  },
  {
    id: 'srv-2',
    name: 'Barba',
    durationMin: 30,
    price: 35.00,
    category: 'barba',
    active: true,
    description: 'Barboterapia com toalha quente, óleo e alinhamento',
  },
  {
    id: 'srv-3',
    name: 'Corte + Barba',
    durationMin: 60,
    price: 70.00,
    category: 'combo',
    active: true,
    description: 'Combo completo cabelo e barba com desconto especial',
  },
  {
    id: 'srv-4',
    name: 'Sobrancelha',
    durationMin: 15,
    price: 15.00,
    category: 'estetica',
    active: true,
    description: 'Design de sobrancelha masculino rápido na navalha',
  },
  {
    id: 'srv-5',
    name: 'Bigode',
    durationMin: 10,
    price: 10.00,
    category: 'barba',
    active: true,
    description: 'Aparada e alinhamento do bigode',
  },
  {
    id: 'srv-6',
    name: 'Pigmentação de Barba',
    durationMin: 30,
    price: 40.00,
    category: 'estetica',
    active: true,
    description: 'Correção de falhas com pigmento natural de alta durabilidade',
  },
];

const getTodayString = () => {
  const d = new Date();
  return d.toISOString().split('T')[0];
};

export const initialAppointments: Appointment[] = [
  {
    id: 'apt-1',
    clientName: 'João da Silva',
    clientPhone: '(62) 99999-9999',
    serviceId: 'srv-1',
    serviceName: 'Corte',
    price: 45.00,
    durationMin: 40,
    barberId: 'barber-1',
    barberName: 'João da Silva',
    date: getTodayString(),
    time: '09:00',
    status: 'completed',
    startedAt: '09:00',
    finishedAt: '09:38',
    paymentMethod: 'pix',
    unitId: 'unit-1',
    remindedViaWhatsapp: true,
  },
  {
    id: 'apt-2',
    clientName: 'Carlos Andrade',
    clientPhone: '(62) 98888-7777',
    serviceId: 'srv-2',
    serviceName: 'Barba',
    price: 35.00,
    durationMin: 30,
    barberId: 'barber-1',
    barberName: 'João da Silva',
    date: getTodayString(),
    time: '09:40',
    status: 'in_progress',
    startedAt: '09:40',
    unitId: 'unit-1',
    remindedViaWhatsapp: true,
  },
  {
    id: 'apt-3',
    clientName: 'Ana Clara',
    clientPhone: '(62) 97777-1111',
    serviceId: 'srv-3',
    serviceName: 'Corte + Barba',
    price: 70.00,
    durationMin: 60,
    barberId: 'barber-1',
    barberName: 'João da Silva',
    date: getTodayString(),
    time: '10:20',
    status: 'scheduled',
    unitId: 'unit-1',
  },
  {
    id: 'apt-4',
    clientName: 'Pedro Henrique',
    clientPhone: '(62) 96666-2222',
    serviceId: 'srv-1',
    serviceName: 'Corte',
    price: 45.00,
    durationMin: 40,
    barberId: 'barber-1',
    barberName: 'João da Silva',
    date: getTodayString(),
    time: '11:20',
    status: 'scheduled',
    unitId: 'unit-1',
  },
  {
    id: 'apt-5',
    clientName: 'Lucas Lima',
    clientPhone: '(62) 95555-3333',
    serviceId: 'srv-4',
    serviceName: 'Sobrancelha',
    price: 15.00,
    durationMin: 15,
    barberId: 'barber-1',
    barberName: 'João da Silva',
    date: getTodayString(),
    time: '12:00',
    status: 'scheduled',
    unitId: 'unit-1',
  },
  {
    id: 'apt-6',
    clientName: 'Gabriel Costa',
    clientPhone: '(62) 94444-4444',
    serviceId: 'srv-3',
    serviceName: 'Corte + Barba',
    price: 70.00,
    durationMin: 60,
    barberId: 'barber-2',
    barberName: 'Carlos Eduardo',
    date: getTodayString(),
    time: '14:00',
    status: 'scheduled',
    unitId: 'unit-1',
  },
  {
    id: 'apt-7',
    clientName: 'Fernando Ramos',
    clientPhone: '(62) 93333-5555',
    serviceId: 'srv-1',
    serviceName: 'Corte',
    price: 45.00,
    durationMin: 40,
    barberId: 'barber-3',
    barberName: 'Mateus Santos',
    date: getTodayString(),
    time: '15:00',
    status: 'scheduled',
    unitId: 'unit-1',
  },
];

export const initialClients: ClientProfile[] = [
  {
    id: 'cli-1',
    name: 'João da Silva',
    phone: '(62) 99999-9999',
    birthday: '1992-08-14',
    lastVisitDate: getTodayString(),
    daysSinceLastVisit: 0,
    totalVisits: 14,
    totalSpent: 980.00,
    favoriteBarberId: 'barber-1',
    favoriteBarberName: 'João da Silva',
    tags: ['VIP', 'Frequente'],
    preferredService: 'Corte + Barba',
  },
  {
    id: 'cli-2',
    name: 'Carlos Andrade',
    phone: '(62) 98888-7777',
    birthday: '1988-11-20',
    lastVisitDate: getTodayString(),
    daysSinceLastVisit: 0,
    totalVisits: 8,
    totalSpent: 560.00,
    favoriteBarberId: 'barber-1',
    favoriteBarberName: 'João da Silva',
    tags: ['Frequente'],
    preferredService: 'Barba',
  },
  {
    id: 'cli-3',
    name: 'Roberto Lima',
    phone: '(62) 97777-6666',
    birthday: '1990-03-10',
    lastVisitDate: '2026-06-15',
    daysSinceLastVisit: 41,
    totalVisits: 18,
    totalSpent: 1250.00,
    favoriteBarberId: 'barber-2',
    favoriteBarberName: 'Carlos Eduardo',
    tags: ['VIP', 'Em Risco', 'Sumiu'],
    preferredService: 'Corte + Barba',
    notes: 'Gosta do café bem quente sem açúcar',
  },
  {
    id: 'cli-4',
    name: 'Marcos Paulo',
    phone: '(62) 96666-5555',
    birthday: '1995-05-22',
    lastVisitDate: '2026-06-25',
    daysSinceLastVisit: 31,
    totalVisits: 6,
    totalSpent: 420.00,
    favoriteBarberId: 'barber-1',
    favoriteBarberName: 'João da Silva',
    tags: ['Em Risco'],
    preferredService: 'Corte',
  },
  {
    id: 'cli-5',
    name: 'Diego Souza',
    phone: '(62) 95555-4444',
    birthday: '1999-01-05',
    lastVisitDate: '2026-07-20',
    daysSinceLastVisit: 6,
    totalVisits: 2,
    totalSpent: 140.00,
    favoriteBarberId: 'barber-3',
    favoriteBarberName: 'Mateus Santos',
    tags: ['Novo'],
    preferredService: 'Corte + Barba',
  },
];

export const initialProducts: InventoryProduct[] = [
  {
    id: 'prod-1',
    name: 'Pomada Modeladora Matte Effect 150g',
    category: 'pomada',
    itemType: 'venda',
    stock: 18,
    minStock: 5,
    costPrice: 22.00,
    sellPrice: 45.00,
    unit: 'unidade',
  },
  {
    id: 'prod-2',
    name: 'Óleo de Barba Hidratante Premium 30ml',
    category: 'barba',
    itemType: 'venda',
    stock: 3, // Low stock alert!
    minStock: 5,
    costPrice: 18.00,
    sellPrice: 38.00,
    unit: 'frasco',
  },
  {
    id: 'prod-3',
    name: 'Shampoo Cabelo & Barba Refresh 300ml',
    category: 'shampoo',
    itemType: 'venda',
    stock: 12,
    minStock: 4,
    costPrice: 20.00,
    sellPrice: 42.00,
    unit: 'frasco',
  },
  {
    id: 'prod-4',
    name: 'Caixa de Lâmina Descartável Platinum (100un)',
    category: 'descartavel',
    itemType: 'insumo',
    stock: 2, // Low stock alert!
    minStock: 5,
    costPrice: 15.00,
    sellPrice: 30.00,
    unit: 'caixa',
  },
  {
    id: 'prod-5',
    name: 'Cerveja Long Neck IPA Premium',
    category: 'bebida',
    itemType: 'venda',
    stock: 24,
    minStock: 10,
    costPrice: 6.00,
    sellPrice: 12.00,
    unit: 'garrafa',
  },
  {
    id: 'prod-6',
    name: 'Gola Higiênica Descartável (Rolo 500un)',
    category: 'descartavel',
    itemType: 'insumo',
    stock: 4,
    minStock: 3,
    costPrice: 18.00,
    sellPrice: 0.00,
    unit: 'rolo',
  },
];

export const initialTransactions: FinancialTransaction[] = [
  {
    id: 'tx-1',
    type: 'income',
    description: 'Atendimento Corte - João da Silva',
    amount: 45.00,
    paymentMethod: 'pix',
    date: getTodayString(),
    time: '09:38',
    barberId: 'barber-1',
    appointmentId: 'apt-1',
    category: 'servico',
  },
  {
    id: 'tx-2',
    type: 'income',
    description: 'Venda Pomada Matte Effect',
    amount: 45.00,
    paymentMethod: 'card_credit',
    date: getTodayString(),
    time: '09:40',
    barberId: 'barber-1',
    category: 'produto',
  },
];

export const initialShopConfig: ShopConfig = {
  shopName: 'Barbearia Barbershop',
  ownerName: 'Proprietário',
  shopPhone: '(62) 99999-0001',
  slug: 'barbearia-barbershop',
  tenantType: 'barbershop',
  currentUnitId: 'unit-1',
  dailyRevenueTarget: 550.00,
  bufferMinutes: 5,
  weeklySchedule: [
    { dayOfWeek: 1, dayName: 'Segunda', openTime: '08:00', closeTime: '19:00', isOpen: true, breakStart: '12:00', breakEnd: '13:00' },
    { dayOfWeek: 2, dayName: 'Terça', openTime: '08:00', closeTime: '19:00', isOpen: true, breakStart: '12:00', breakEnd: '13:00' },
    { dayOfWeek: 3, dayName: 'Quarta', openTime: '08:00', closeTime: '19:00', isOpen: true, breakStart: '12:00', breakEnd: '13:00' },
    { dayOfWeek: 4, dayName: 'Quinta', openTime: '08:00', closeTime: '19:00', isOpen: true, breakStart: '12:00', breakEnd: '13:00' },
    { dayOfWeek: 5, dayName: 'Sexta', openTime: '08:00', closeTime: '19:00', isOpen: true, breakStart: '12:00', breakEnd: '13:00' },
    { dayOfWeek: 6, dayName: 'Sábado', openTime: '08:00', closeTime: '16:00', isOpen: true, breakStart: '12:00', breakEnd: '13:00' },
    { dayOfWeek: 0, dayName: 'Domingo', openTime: '09:00', closeTime: '13:00', isOpen: false },
  ],
  whatsappAutoSend: true,
  tvBannerMessage: 'BOM DIA! FOCO, DISCIPLINA E CONSTÂNCIA!',
};
